/* Comum para opções de organização: */
INSERT INTO TEMAS VALUES(1,'TODOS'); 

/* Populando a tabela TEMAS */
INSERT INTO TEMAS VALUES(NULL,'Python');
INSERT INTO TEMAS VALUES(NULL,'Rubi');
INSERT INTO TEMAS VALUES(NULL,'C');
INSERT INTO TEMAS VALUES(NULL,'C#');
INSERT INTO TEMAS VALUES(NULL,'Delphi');
INSERT INTO TEMAS VALUES(NULL,'Java');
INSERT INTO TEMAS VALUES(NULL,'Javascript');
INSERT INTO TEMAS VALUES(NULL,'React');
INSERT INTO TEMAS VALUES(NULL,'Machine Learning');
INSERT INTO TEMAS VALUES(NULL,'Flutter');
INSERT INTO TEMAS VALUES(NULL,'AWS');
INSERT INTO TEMAS VALUES(NULL,'Rubi on Rails');
INSERT INTO TEMAS VALUES(NULL,'Business Intelligence');
INSERT INTO TEMAS VALUES(NULL,'Big Data');
INSERT INTO TEMAS VALUES(NULL,'Deep Learning');
INSERT INTO TEMAS VALUES(NULL,'PHP');